import Head from "next/head";
import { useEffect, useState } from "react";
import { Input, Table, Button } from "antd";
import { useRouter } from "next/router";
import styles from "../../styles/Home.module.css";



const { Search } = Input;

export default function Home() {
  const [users, setUsers] = useState([]);
  const [user, setUser] = useState([]);
  const router= useRouter();

  useEffect(() => {
    const headers = new Headers();
    headers.append("Accept", "application/vnd.github+json");
    headers.append("Authorization", process.env.NEXT_PUBLIC_TOKEN_GITHUB);

    fetch("https://api.github.com/users", { headers })
      .then((response) => response.json())
      .then((result) => setUsers(result))
      .catch((error) => console.log("error", error));
  }, []);

  const onSearch = (value) => {
    const userSerch = users?.filter((elem) => elem.login == value);
    setUser(userSerch);

  };

  const columnsUser = [
    {
      title: 'Nick',
      dataIndex: 'login',
      key: 'login',
    },
    {
      title: 'Profile',
      dataIndex: 'url',
      key: 'url',
      render: (url) => <a href={url}>{url}</a>,

    },
  ];

  return (
    <div>
      <Head>
        <title>GitHub App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>Search for User &rarr;</h2>
          </div>

          <div className={styles.card}>
            <Search
              placeholder="search user"
              onSearch={onSearch}
              enterButton
            />
          </div>
        </div>
       <div>
        <Table columns={columnsUser} dataSource={user} />
        </div>
        <div>
        <Button  onClick={() => router.back()} type="primary">Go Back</Button>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          By {"Mar"}
        </a>
      </footer>
    </div>
  );
}
