import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import { Input } from "antd";

import styles from "../styles/Home.module.css";

const { Search } = Input;

export default function Home() {
  const [user, setUser] = useState([]);

  useEffect(() => {
    const headers = new Headers();
    headers.append("Accept", "application/vnd.github+json");
    headers.append("Authorization", "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");

    fetch("https://api.github.com/users", { headers })
      .then((response) => response.json())
      .then((result) => setUser(result))
      .catch((error) => console.log("error", error));
  }, []);

  const onSearch = (value) => {
    debugger;
    const userSerch = user?.filter((elem) => elem.login == value);

    console.log("userSerch", userSerch);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>GitHub App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Search for GitHub</h1>

        <div className={styles.grid}>
          <div className={styles.card}>
            <a href="/users">
              <h2>For friends &rarr;</h2>
            </a>
          </div>
        </div>
        <div className={styles.grid}>
          <div className={styles.card}>
            <a href="/repositories">
              <h2>For Repos &rarr;</h2>
            </a>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          By {"Mar"}
        </a>
      </footer>
    </div>
  );
}
